### ISSUE TITLE
Add way to initialize (remove old) log (like ensureDelete) 

### ISSUE THREAD

**Issue by fuhrmanator** [jecisc/TinyLogger#14]
When I use TinyLogger on a file, I would like to say that the file should be overwritten (before TinyLogger, I was using `'Mining.log' asFileReference ensureDelete; writeStreamDo: [...]`. Otherwise, I have to remove it by hand.

**Comment by jecisc** [comment]
I finished the features. I'll add all the doc in one time before the release.
